import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — FreeAIBypass",
  description: "FreeAIBypass terms of service. Read our terms before using our free AI humanizer tool.",
  alternates: { canonical: "https://freeaibypass.com/terms" },
};

export default function Terms() {
  const C = {
    bg: "#07070f", card: "#0e0e1a", card2: "#12121f", border: "#1e1e35",
    purple: "#8b5cf6", blue: "#3b82f6", text: "#e2e2f0", textMid: "#8888aa", textDim: "#44445a",
  };

  const sections = [
    { title: "Acceptance of Terms", content: "By accessing and using FreeAIBypass, you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service. We reserve the right to update these terms at any time, and your continued use of the service constitutes acceptance of any changes." },
    { title: "Description of Service", content: "FreeAIBypass provides a free AI text humanization service that rewrites AI-generated content to produce more natural, human-sounding prose. The service is provided as-is and is intended to help users improve the readability and naturalness of AI-assisted writing. We make no guarantees about the effectiveness of the humanization for any specific purpose." },
    { title: "Acceptable Use", content: "You agree to use FreeAIBypass only for lawful purposes. You may not use the service to produce content that infringes on the intellectual property rights of others, to generate content intended to deceive or defraud, or to produce material that violates any applicable laws or regulations. You are solely responsible for the content you submit and the use you make of any output." },
    { title: "Academic Integrity", content: "FreeAIBypass is a writing assistance tool. Users are solely responsible for ensuring that their use of this tool complies with the academic integrity policies of their institution. We strongly encourage users to review their institution's policies on AI-assisted writing before submitting any work for academic credit. FreeAIBypass accepts no responsibility for any academic integrity violations that may result from the misuse of our service." },
    { title: "Intellectual Property", content: "The text you submit to FreeAIBypass remains your intellectual property. The humanized output generated by our service is also yours to use as you see fit, subject to any rights held by the original content creator. FreeAIBypass does not claim any ownership over input or output content." },
    { title: "Disclaimer of Warranties", content: "FreeAIBypass is provided on an as-is and as-available basis without any warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, error-free, or that the output will meet your specific requirements. The effectiveness of AI humanization varies by content type, detector, and other factors outside our control." },
    { title: "Limitation of Liability", content: "To the fullest extent permitted by law, FreeAIBypass shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service. This includes but is not limited to academic consequences, reputational harm, or any other losses arising from reliance on our service output." },
    { title: "Termination", content: "We reserve the right to suspend or terminate access to FreeAIBypass at any time, for any reason, without notice. We may also discontinue the service entirely at any time. We will make reasonable efforts to provide advance notice of any planned service discontinuation." },
    { title: "Governing Law", content: "These terms shall be governed by and construed in accordance with applicable law. Any disputes arising from these terms or your use of FreeAIBypass shall be resolved through good-faith negotiation where possible." },
    { title: "Contact", content: "If you have any questions about these terms, please contact us at venomdesire40@gmail.com." },
  ];

  return (
    <div style={{ minHeight: "100vh", background: C.bg, color: C.text, fontFamily: "system-ui,-apple-system,sans-serif" }}>
      <style>{`@keyframes fadeIn{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}} a.nav-link:hover{color:#fff!important}`}</style>

      <nav style={{ position: "sticky", top: 0, zIndex: 100, background: "rgba(7,7,15,0.9)", backdropFilter: "blur(20px)", borderBottom: `1px solid ${C.border}`, padding: "0 32px" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto", display: "flex", alignItems: "center", justifyContent: "space-between", height: 64 }}>
          <a href="/" style={{ fontSize: 22, fontWeight: 900, letterSpacing: "-2px", color: "#fff", textDecoration: "none" }}>HUMAN<span style={{ color: C.purple }}>LY</span></a>
          <a href="/" className="nav-link" style={{ fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.15em", color: C.textMid, textDecoration: "none", transition: "color 0.2s" }}>← Back to Home</a>
        </div>
      </nav>

      <div style={{ maxWidth: 860, margin: "0 auto", padding: "64px 24px 96px", animation: "fadeIn 0.7s ease forwards" }}>

        <div style={{ marginBottom: 56 }}>
          <p style={{ fontSize: 10, fontWeight: 900, letterSpacing: "0.4em", textTransform: "uppercase", color: C.purple, marginBottom: 16 }}>Legal</p>
          <h1 style={{ fontSize: "clamp(32px,6vw,52px)", fontWeight: 900, color: "#fff", letterSpacing: "-2px", lineHeight: 1.1, marginBottom: 20 }}>Terms of Service</h1>
          <p style={{ fontSize: 13, color: C.textDim, fontWeight: 600 }}>Last updated: {new Date().getFullYear()}</p>
          <div style={{ height: 2, width: 80, background: `linear-gradient(90deg, ${C.purple}, transparent)`, borderRadius: 2, marginTop: 16 }} />
        </div>

        <div style={{ padding: 32, background: "rgba(139,92,246,0.08)", border: `1px solid rgba(139,92,246,0.2)`, borderRadius: 20, marginBottom: 40 }}>
          <p style={{ fontSize: 15, color: C.text, lineHeight: 1.9, margin: 0 }}>
            Please read these terms carefully before using FreeAIBypass. By using our service, you agree to be bound by these terms. These terms are designed to be straightforward and fair — we want you to understand exactly what you are agreeing to.
          </p>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
          {sections.map((s, i) => (
            <div key={i} style={{ padding: 36, background: C.card, border: `1px solid ${C.border}`, borderRadius: 24 }}>
              <h2 style={{ fontSize: 18, fontWeight: 700, color: "#fff", marginBottom: 14, letterSpacing: "-0.3px" }}>{s.title}</h2>
              <p style={{ fontSize: 14, color: C.textMid, lineHeight: 1.9, margin: 0 }}>{s.content}</p>
            </div>
          ))}
        </div>

        <div style={{ marginTop: 48, textAlign: "center" }}>
          <a href="/" style={{ display: "inline-block", padding: "14px 36px", background: `linear-gradient(135deg, ${C.purple}, ${C.blue})`, color: "#fff", textDecoration: "none", borderRadius: 12, fontSize: 12, fontWeight: 900, textTransform: "uppercase", letterSpacing: "0.2em" }}>← Back to Tool</a>
        </div>
      </div>

      <footer style={{ borderTop: `1px solid ${C.border}`, padding: "40px 24px", display: "flex", flexDirection: "column", alignItems: "center", gap: 16 }}>
        <a href="/" style={{ fontSize: 22, fontWeight: 900, letterSpacing: "-2px", color: "#fff", textDecoration: "none" }}>HUMAN<span style={{ color: C.purple }}>LY</span></a>
        <nav style={{ display: "flex", gap: 24 }}>
          {[{ label: "About", href: "/about" }, { label: "Privacy", href: "/privacy" }].map((link) => (
            <a key={link.label} href={link.href} className="nav-link" style={{ fontSize: 10, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.2em", color: C.textDim, textDecoration: "none", transition: "color 0.2s" }}>{link.label}</a>
          ))}
        </nav>
        <p style={{ fontSize: 10, color: C.textDim, margin: 0 }}>© {new Date().getFullYear()} FreeAIBypass. All rights reserved.</p>
      </footer>
    </div>
  );
}